# Generated by Django 2.2.14 on 2021-04-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('stars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('person1', models.CharField(max_length=20, null=True)),
                ('person2', models.CharField(max_length=20, null=True)),
                ('person3', models.CharField(max_length=20, null=True)),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
