# Generated by Django 2.2.14 on 2021-04-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_questboard_questcards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questcard',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
