# Generated by Django 2.2.14 on 2021-04-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210401_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questboard',
            name='questcards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Questcard'),
        ),
    ]
