# Generated by Django 2.2.14 on 2021-04-01 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210402_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questcard',
            name='questboard',
        ),
        migrations.AddField(
            model_name='questboard',
            name='questcards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Questcard'),
        ),
    ]
