# Generated by Django 2.2.14 on 2021-04-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210402_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questboard',
            name='questcards',
        ),
        migrations.AddField(
            model_name='questboard',
            name='questcards',
            field=models.ManyToManyField(to='main.Questcard'),
        ),
    ]
