# Generated by Django 2.2.14 on 2021-04-01 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_questboard_questcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='questboard',
            name='questcards',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Questcard'),
            preserve_default=False,
        ),
    ]
