# Generated by Django 2.2.14 on 2021-04-01 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210402_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questcard',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='questcard',
            old_name='name',
            new_name='quest',
        ),
        migrations.RenameField(
            model_name='questcard',
            old_name='stars',
            new_name='starquest',
        ),
        migrations.RemoveField(
            model_name='questboard',
            name='questcards',
        ),
        migrations.RemoveField(
            model_name='questcard',
            name='id',
        ),
        migrations.AddField(
            model_name='questcard',
            name='questboard_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Questboard'),
            preserve_default=False,
        ),
    ]
