# Generated by Django 2.2.14 on 2021-04-02 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210402_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questcard',
            old_name='starquest',
            new_name='stars',
        ),
        migrations.RemoveField(
            model_name='questcard',
            name='questboard_ptr',
        ),
        migrations.AddField(
            model_name='questboard',
            name='questcards',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Questcard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questcard',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
