# Generated by Django 2.2.14 on 2021-04-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210402_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='addPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slot', models.CharField(choices=[('Slot 1', 'Slot 1'), ('Slot 2', 'Slot 2'), ('Slot 3', 'Slot 3')], max_length=10)),
            ],
        ),
    ]
