# Generated by Django 2.2.14 on 2021-04-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_addperson1_addperson2_addperson3'),
    ]

    operations = [
        migrations.CreateModel(
            name='addPersonOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
    ]
