# Generated by Django 2.2.14 on 2021-04-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_addpersonthree_addpersontwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpersonone',
            name='slot',
            field=models.CharField(choices=[('Slot 1', 'Slot 1'), ('---', '---')], default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addpersonthree',
            name='slot',
            field=models.CharField(choices=[('Slot 3', 'Slot 3'), ('---', '---')], default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addpersontwo',
            name='slot',
            field=models.CharField(choices=[('Slot 2', 'Slot 2'), ('---', '---')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
