# Generated by Django 2.2.14 on 2021-04-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210410_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='questcard',
            name='is_for_everyone',
            field=models.BooleanField(default='False'),
        ),
    ]
